In [1]:
import duckdb

caminho_banco = r"D:\Laboratorio\Projetos_Anhanguera_POS_GRAD\modulo_2\projeto\Modulo_2\dados_duckdb.db"
con = duckdb.connect(database=caminho_banco, read_only=False)

df = con.execute("SELECT * FROM bronze_z0019").fetchdf()
display(df.head(10)) # Mostra as 10 primeiras linhas

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022
2,10003,PREGO,BT10,100,50,z0019_1.csv,2026-08-25 16:47:52.588022
3,10004,SERRA,BT50,100,200,z0019_2.csv,2026-08-25 16:47:52.589174
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174
5,10003,PREGO,BT10,100,60,z0019_2.csv,2026-08-25 16:47:52.589174

In [2]:
df = con.execute("""
                SELECT *
                FROM bronze_z0019
                WHERE data_ingestao >= '2026-08-25'
                """).fetch_df()
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022
2,10003,PREGO,BT10,100,50,z0019_1.csv,2026-08-25 16:47:52.588022
3,10004,SERRA,BT50,100,200,z0019_2.csv,2026-08-25 16:47:52.589174
4,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174

In [3]:
df = con.execute("""
                SELECT *, ROW_NUMBER () OVER (PARTITION BY NATBR ORDER BY data_ingestao DESC) AS row 
                FROM bronze_z0019
                WHERE data_ingestao >= '2026-08-25'
                """).fetch_df()
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao,row
0,10003,PREGO,BT10,100,60,z0019_2.csv,2026-08-25 16:47:52.589174,1
1,10003,PREGO,BT10,100,50,z0019_1.csv,2026-08-25 16:47:52.588022,2
2,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174,1
4,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022,1

In [4]:
df = con.execute("""
                SELECT *
                FROM (
                    SELECT *, ROW_NUMBER () OVER (PARTITION BY NATBR ORDER BY data_ingestao DESC) AS row 
                    FROM bronze_z0019
                    WHERE data_ingestao >= '2026-08-25'
                )
                """).fetch_df()
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao,row
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022,1
2,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174,1
3,10004,SERRA,BT50,100,200,z0019_2.csv,2026-08-25 16:47:52.589174,1
4,10003,PREGO,BT10,100,60,z0019_2.csv,2026-08-25 16:47:52.589174,1

In [6]:
df = con.execute("""
                SELECT *
                FROM (
                    SELECT *, ROW_NUMBER () OVER (PARTITION BY NATBR ORDER BY data_ingestao DESC) AS row 
                    FROM bronze_z0019
                    WHERE data_ingestao >= '2026-08-25'
                ) WHERE row = 1
                """).fetch_df()
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao,row
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022,1
2,10004,SERRA,BT50,100,200,z0019_2.csv,2026-08-25 16:47:52.589174,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174,1
4,10003,PREGO,BT10,100,60,z0019_2.csv,2026-08-25 16:47:52.589174,1

In [7]:
df.head(10)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_ingestao,data_ingestao,row
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-08-25 16:47:52.588022,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-08-25 16:47:52.588022,1
2,10004,SERRA,BT50,100,200,z0019_2.csv,2026-08-25 16:47:52.589174,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-08-25 16:47:52.589174,1
4,10003,PREGO,BT10,100,60,z0019_2.csv,2026-08-25 16:47:52.589174,1

In [ ]:
df_final = df.drop(columns=['nome_ingestao', 'data_ingestao', 'row'], )
df_final = df_final.rename(columns={"NATBR":"id"})
df_final = df_final.rename(columns={"MAKTX":"nm_produto"})
df_final = df_final.rename(columns={"WERKS":"id_categoria"})
df_final = df_final.rename(columns={"MAINS":"id_fornecedor"})
df_final = df_final.rename(columns={"LABST":"vl_preco"})
df_final.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100       100
1  10002    MARTELO         BT50            100      1500
2  10004      SERRA         BT50            100       200
3  10005    MACHADO         BT50            100       100
4  10003      PREGO         BT10            100        60

In [15]:
df_final.dtypes

id               int64
nm_produto         str
id_categoria       str
id_fornecedor    int64
vl_preco         int64
dtype: object

In [18]:
df2 = df_final
df2 = df2.astype(
    {
        'id': 'int',
        'nm_produto': 'str',
        'id_categoria': 'str',
        'id_fornecedor': 'int',
        'vl_preco': 'float'
    }
)

df_final.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100       100
1  10002    MARTELO         BT50            100      1500
2  10004      SERRA         BT50            100       200
3  10005    MACHADO         BT50            100       100
4  10003      PREGO         BT10            100        60

In [19]:
df2.dtypes

id                 int64
nm_produto           str
id_categoria         str
id_fornecedor      int64
vl_preco         float64
dtype: object

In [20]:
con.execute("""
CREATE TABLE IF NOT EXISTS produtos (
            id BIGINT,
            nm_produto TEXT,
            id_categoria TEXT,
            id_fornecedor BIGINT,
            vl_preco FLOAT
            )
""")

In [21]:
df2.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10004      SERRA         BT50            100     200.0
3  10005    MACHADO         BT50            100     100.0
4  10003      PREGO         BT10            100      60.0

In [27]:
con.execute("INSERT INTO produtos SELECT * FROM df2")

In [28]:
df_resultado = con.execute("SELECT * FROM produtos").fetchdf()
df_resultado.head(10)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100    1500.0
2  10004      SERRA         BT50            100     200.0
3  10005    MACHADO         BT50            100     100.0
4  10003      PREGO         BT10            100      60.0

In [29]:
con.close()