In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False) #criar arquivo local

In [3]:
df = pd.read_csv('../landing/z0019_1.csv') 
df.head()

  NATBR;MAKTX;WERKS;MAINS;LABST
0   10001;PARAFUSO;BT10;100;100
1   10002;MARTELO;BT50;100;1500
2       10003;PREGO;BT10;100;50

In [4]:
df = pd.read_csv('../landing/z0019_1.csv', sep=';') #separador pelo ponto e virgula
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST
0  10001  PARAFUSO  BT10    100    100
1  10002   MARTELO  BT50    100   1500
2  10003     PREGO  BT10    100     50

In [5]:
arquivo = 'z0019_1.csv'
df = pd.read_csv(f'../landing/{arquivo}', sep=';') #indicador de formação mais adição do arquivo na coluna
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST
0  10001  PARAFUSO  BT10    100    100
1  10002   MARTELO  BT50    100   1500
2  10003     PREGO  BT10    100     50

In [6]:
print(datetime.now())

2026-08-25 16:44:08.407382

In [7]:
arquivo = 'z0019_1.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-08-25 16:44:10.222179
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-08-25 16:44:10.222179
2  10003     PREGO  BT10    100     50  z0019_1.csv 2026-08-25 16:44:10.222179

In [8]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_ingestao VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [9]:
resultado = con.execute("SELECT * FROM bronze_produtos").fetchdf()
print(resultado)

Empty DataFrame
Columns: [NATBR, MAKTX, WERKS, MAINS, LABST, nome_ingestao, data_ingestao]
Index: []

In [10]:
resultado.head()

Empty DataFrame
Columns: [NATBR, MAKTX, WERKS, MAINS, LABST, nome_ingestao, data_ingestao]
Index: []

In [11]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df") #inserção dos dados no dataframe

In [12]:
resultado = con.execute("SELECT * FROM bronze_produtos").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_ingestao              data_ingestao
0  10001  PARAFUSO  BT10   100   100   z0019_1.csv 2026-08-25 16:44:10.222179
1  10002   MARTELO  BT50   100  1500   z0019_1.csv 2026-08-25 16:44:10.222179
2  10003     PREGO  BT10   100    50   z0019_1.csv 2026-08-25 16:44:10.222179

In [13]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-08-25 16:44:48.794694
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-08-25 16:44:48.794694
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-08-25 16:44:48.794694

In [14]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_ingestao VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [15]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [16]:
resultado = con.execute("SELECT * FROM bronze_produtos").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_ingestao              data_ingestao
0  10001  PARAFUSO  BT10   100   100   z0019_1.csv 2026-08-25 16:44:10.222179
1  10002   MARTELO  BT50   100  1500   z0019_1.csv 2026-08-25 16:44:10.222179
2  10003     PREGO  BT10   100    50   z0019_1.csv 2026-08-25 16:44:10.222179
3  10004     SERRA  BT50   100   200   z0019_2.csv 2026-08-25 16:44:48.794694
4  10005   MACHADO  BT50   100   100   z0019_2.csv 2026-08-25 16:44:48.794694
5  10003     PREGO  BT10   100    60   z0019_2.csv 2026-08-25 16:44:48.794694

In [17]:
# 1. Apaga a tabela bronze_z0019 que já existia no arquivo de banco de dados
con.execute("DROP TABLE IF EXISTS bronze_z0019")

In [18]:
# 2. Agora sim, renomeia a tabela atual para bronze_z0019
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [ ]:
# 3. Visualiza para confirmar se deu certo
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

In [19]:
df = con.execute("SELECT * FROM bronze_z0019").fetchdf()
df.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_ingestao              data_ingestao
0  10001  PARAFUSO  BT10   100   100   z0019_1.csv 2026-08-25 16:44:10.222179
1  10002   MARTELO  BT50   100  1500   z0019_1.csv 2026-08-25 16:44:10.222179
2  10003     PREGO  BT10   100    50   z0019_1.csv 2026-08-25 16:44:10.222179
3  10004     SERRA  BT50   100   200   z0019_2.csv 2026-08-25 16:44:48.794694
4  10005   MACHADO  BT50   100   100   z0019_2.csv 2026-08-25 16:44:48.794694
5  10003     PREGO  BT10   100    60   z0019_2.csv 2026-08-25 16:44:48.794694

In [21]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_ingestao              data_ingestao
0  10001  PARAFUSO  BT10   100   100   z0019_1.csv 2026-08-25 16:44:10.222179
1  10002   MARTELO  BT50   100  1500   z0019_1.csv 2026-08-25 16:44:10.222179
2  10003     PREGO  BT10   100    50   z0019_1.csv 2026-08-25 16:44:10.222179
3  10004     SERRA  BT50   100   200   z0019_2.csv 2026-08-25 16:44:48.794694
4  10005   MACHADO  BT50   100   100   z0019_2.csv 2026-08-25 16:44:48.794694
5  10003     PREGO  BT10   100    60   z0019_2.csv 2026-08-25 16:44:48.794694

In [22]:
con.close()

In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

# 1. Caminhos absolutos
caminho_banco = r"D:\Laboratorio\Projetos_Anhanguera_POS_GRAD\modulo_2\projeto\Modulo_2\dados_duckdb.db"
pasta_landing = r"D:\Laboratorio\Projetos_Anhanguera_POS_GRAD\modulo_2\projeto\Modulo_2\landing"
con = duckdb.connect(database=caminho_banco, read_only=False)

# 2. Lendo o PRIMEIRO arquivo
arquivo1 = 'z0019_1.csv'
df1 = pd.read_csv(os.path.join(pasta_landing, arquivo1), sep=';')
df1['nome_ingestao'] = arquivo1
df1['data_ingestao'] = datetime.now()

# 3. Lendo o SEGUNDO arquivo
arquivo2 = 'z0019_2.csv'
df2 = pd.read_csv(os.path.join(pasta_landing, arquivo2), sep=';')
df2['nome_ingestao'] = arquivo2
df2['data_ingestao'] = datetime.now()

# 4. Juntando (concatenando) os dois DataFrames em um só
df_final = pd.concat([df1, df2], ignore_index=True)

# 5. Apaga as tabelas antigas para não dar erro de duplicidade
con.execute("DROP TABLE IF EXISTS bronze_produtos")
con.execute("DROP TABLE IF EXISTS bronze_z0019")

# 6. Cria a tabela final no DuckDB com os 10 registros (5 de cada arquivo)
con.execute("CREATE TABLE bronze_z0019 AS SELECT * FROM df_final")

# 7. Salva e fecha a conexão
con.close()
print(f"Ingestão concluída! Total de registros salvos: {len(df_final)}")

Ingestão concluída! Total de registros salvos: 6